version: '3.1'
services:
  backend:
    command: gunicorn --bind 0.0.0.0:5000 --reload wsgi:app
    volumes:
      - ./backend:/usr/src/app
  frontend:
    command: ./node_modules/.bin/next dev
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app