from .alerts import alert_bp
from .auth import auth_bp
from .endpoints import endpoint_bp
from .gates import gate_bp
from .logs import log_bp
from .system import system_bp
from .users import user_bp
from .cameras import camera_bp
from .config import config_bp