"""Added relation from user to activity

Revision ID: 3e823f28ca4f
Revises: e48f616f67a3
Create Date: 2020-06-07 22:05:58.923657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e823f28ca4f'
down_revision = 'e48f616f67a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_column('activity', 'user')
    # ### end Alembic commands ###
