"""empty message

Revision ID: 488b3fab4f2c
Revises: 
Create Date: 2020-07-27 19:49:15.895076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488b3fab4f2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('gate', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('meta', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'activity', 'gate', ['gate'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_column('activity', 'meta')
    op.drop_column('activity', 'gate')
    # ### end Alembic commands ###
