"""empty message

Revision ID: 6c22d521603b
Revises: 8a0c67d198db
Create Date: 2022-03-23 16:04:27.692712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c22d521603b'
down_revision = '8a0c67d198db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('reason', sa.String(length=64), nullable=True))
    op.execute("""UPDATE "log" SET reason = 'success' WHERE result = true""")
    op.execute("""UPDATE "log" SET reason = 'disabled' WHERE result = false""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'reason')
    # ### end Alembic commands ###
