"""empty message

Revision ID: 8bda326178d9
Revises: 6c22d521603b
Create Date: 2022-03-23 21:21:20.725859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bda326178d9'
down_revision = '6c22d521603b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('camera_uri', sa.String(length=256), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('camera_status', sa.Column('camera', sa.Integer(), nullable=True))
    op.drop_constraint('camera_status_gate_fkey', 'camera_status', type_='foreignkey')
    op.create_foreign_key(None, 'camera_status', 'camera', ['camera'], ['id'])
    op.drop_column('camera_status', 'gate')
    op.add_column('gate', sa.Column('camera_general', sa.Integer(), nullable=True))
    op.add_column('gate', sa.Column('camera_alpr', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gate', 'camera', ['camera_alpr'], ['id'])
    op.create_foreign_key(None, 'gate', 'camera', ['camera_general'], ['id'])
    op.drop_column('gate', 'camera_uri')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gate', sa.Column('camera_uri', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gate', type_='foreignkey')
    op.drop_constraint(None, 'gate', type_='foreignkey')
    op.drop_column('gate', 'camera_alpr')
    op.drop_column('gate', 'camera_general')
    op.add_column('camera_status', sa.Column('gate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'camera_status', type_='foreignkey')
    op.create_foreign_key('camera_status_gate_fkey', 'camera_status', 'gate', ['gate'], ['id'])
    op.drop_column('camera_status', 'camera')
    op.drop_table('config')
    op.drop_table('camera')
    # ### end Alembic commands ###
