"""empty message

Revision ID: a3a0c9bd9df9
Revises: 8bda326178d9
Create Date: 2022-05-09 22:37:25.016416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a0c9bd9df9'
down_revision = '8bda326178d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirm_modal', sa.Boolean(), nullable=True))
    op.execute("""UPDATE "user" SET confirm_modal = true""")
    op.alter_column('user', 'confirm_modal', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirm_modal')
    # ### end Alembic commands ###
