"""Initial migration

Revision ID: e48f616f67a3
Revises: 
Create Date: 2020-06-06 20:56:32.629147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48f616f67a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('uri_open', sa.String(length=256), nullable=True),
    sa.Column('uri_close', sa.String(length=256), nullable=True),
    sa.Column('uri_rtsp', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('gate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gate'], ['gate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('endpoint', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint'], ['endpoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Integer(), nullable=True),
    sa.Column('access', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('snapshot', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['access'], ['access.id'], ),
    sa.ForeignKeyConstraint(['endpoint'], ['endpoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('access')
    op.drop_table('endpoint')
    op.drop_table('user')
    op.drop_table('gate')
    # ### end Alembic commands ###
